### ISSUE TITLE
power button doesn't work

### ISSUE THREAD

**Issue by Chetan-KK** [Chetan-KK/Windows-10-Clone#2]
let's make power button work.

**Comment by FurrukhJamal** [comment]
what functionality are you looking for with the power button?

**Comment by Chetan-KK** [comment]
didn't think of that but you can use your creativity ✍🏻

these are my opinions:-

- restart: restart animation and then refresh website
- power off: shut down animation for a sec and then black screen and power on button
- sleep: black screen and wake up button

**Comment by FurrukhJamal** [comment]
how about for sleep a black screen and a wakes up on a mouse move or a key press? I don't remember what the real animations were like for windows 10, I could find the animations for the restart but couldnt find one for power off. Do you have any links to that?

**Comment by Chetan-KK** [comment]
just put a simple button for power on and turn off sleep mode

for animation, here you go: https://uiverse.io/SelfMadeSystem/black-yak-68

and put more time to shut down and less for sleeping

best of luck!!

**Comment by FurrukhJamal** [comment]
I have been trying to include testing in the app but have failed so far, do you know how to include Jest, React-testing libraries for testing in a Vite app?

**Comment by Chetan-KK** [comment]
try this: https://zaferayan.medium.com/how-to-setup-jest-and-react-testing-library-in-vite-project-2600f2d04bdd

**Comment by FurrukhJamal** [comment]
have completed sleep and restart features, hopefully would submit a pull request in a day or two when I am done with shutdown feature
