### ISSUE TITLE
[BUG] : Submenu stays open if not clicked and closed manually

### ISSUE THREAD

**Issue by shreysachani** [Chetan-KK/Windows-10-Clone#23]
Issue: 
- When the submenu is not clicked and closed manually it stays open. And also when its open when clicked anywhere else it doesnt 
  close, instead it should close when clicked outside of that specific area.

Steps to Reproduce :
- Click the windows button
- Hover over to the side panel and Click the settings buttons
- Now click directly outside anywhere except for the windows opened section
- Click  again on the windows button
- You will see the submenu for settings stayed open

Fix Plan :
- To solve this issue, I will create a custom React hook that handles the following:

- Detecting clicks outside the submenu area to trigger closing.
- Properly managing the submenu state so that it closes when required (either when the user clicks outside or when manually interacted 
  with).

Additional Context :
- Please refer to the attached video demonstrating the bug.

https://github.com/user-attachments/assets/dcf66240-cfc3-45c7-9b45-8af9494a839f

**Comment by shreysachani** [comment]
Please assign this issue to me under hacktoberfest

**Comment by Chetan-KK** [comment]
Hi @shreysachani  you can make a pr i'll merge it if it solves this issue

**Comment by shreysachani** [comment]
Will start working on this issue.

**Comment by Chetan-KK** [comment]
best of luck 🤞🏻

**Comment by isha-dubey** [comment]
I see you one is assigned to this issue can you please assign this issue to me under hacktoberfest

**Comment by Chetan-KK** [comment]
you can directly start by making pr
